spring.application.name=assessment-service
server.port=8083

# REPLACE <USERNAME> AND <PASSWORD> WITH YOUR ATLAS CREDENTIALS
spring.data.mongodb.uri=mongodb+srv://BytecodeTrainings:Bytecode%401354@bytecodetrainings.4nosy2u.mongodb.net/assessment-db?retryWrites=true&w=majority&appName=BytecodeTrainings
spring.mongodb.uri=mongodb+srv://BytecodeTrainings:Bytecode%401354@bytecodetrainings.4nosy2u.mongodb.net/assessment-db?retryWrites=true&w=majority&appName=BytecodeTrainings
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
