spring.application.name=lead-service
server.port=8089
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# MongoDB Config (Local)
spring.data.mongodb.uri=mongodb://localhost:27017/lead-db
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
