version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: b-ems-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bytecode_ems
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: b-ems-cache
    restart: always
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    container_name: b-ems-backend
    restart: always
    ports:
      - '5001:5001'
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/bytecode_ems?schema=public
      JWT_SECRET: your_super_secret_jwt_key_123
      NODE_ENV: production
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: b-ems-frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5001/api/v1
    depends_on:
      - backend

volumes:
  postgres_data:
