spring.application.name=academic-service
server.port=8089

spring.data.mongodb.uri=mongodb://localhost:27017/academic-db
spring.mongodb.uri=mongodb://localhost:27017/academic-db
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
